From issue_5
version: '3'
services:
  mysql-server:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix_pwd
      - MYSQL_ROOT_PASSWORD=root_pwd
  zabbix-java-gateway:
    image: zabbix/zabbix-java-gateway:latest
  zabbix-server-mysql:
    image: zabbix/zabbix-server-mysql:latest
    environment:
      - DB_SERVER_HOST=mysql-server
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix_pwd
      - MYSQL_ROOT_PASSWORD=root_pwd
      - ZBX_JAVAGATEWAY=zabbix-java-gateway
    links:
      - mysql-server:mysql
      - zabbix-java-gateway:zabbix-java-gateway
    ports:
      - "10051:10051"
  zabbix-web-apache-mysql:
    image: zabbix/zabbix-web-apache-mysql:latest
    environment:
      - DB_SERVER_HOST=mysql-server
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix_pwd
      - MYSQL_ROOT_PASSWORD=root_pwd
    links:
      - mysql-server:mysql
      - zabbix-server-mysql:zabbix-server
    ports:
      - "8005:80"
